repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
        args:
          - --assume-in-merge
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check .
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-check
        name: ruff check - fix
        args: [--fix]
      - id: ruff-format
      - id: ruff-check
      - id: ruff-format
        name: ruff format - check
        args: [--check]
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint
        name: djlint reformat
        args: [--reformat, --quiet]
      - id: djlint
        name: djlint lint
        args: [--lint]
      - id: djlint
        name: djlint check
        args: [--check]
