services:
  www:
    container_name: www
    build:
      context: .
      dockerfile: Containerfile
    expose:
      - 4000
    restart: always
    volumes:
      - static_files:/www/app/static/
  caddy:
    container_name: caddy
    build:
      context: caddy
      dockerfile: Containerfile.local
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - static_files:/srv/static/
volumes:
  static_files:
