services:
  luovkle.com:
    container_name: luovkle.com
    build:
      context: .
      dockerfile: Containerfile
      target: runner
    user: root
    ports:
      - 80:4000
    restart: always
    command: "flask run --debug --port 4000 --host 0.0.0.0"
    volumes:
      - ./app/:/www/app/:z
      - ./content/:/www/content/:z
      - ./scripts/:/www/scripts/:z
  styles:
    container_name: styles
    build:
      context: .
      dockerfile: Containerfile
      target: css-builder
    restart: always
    command: "pnpm run dev:css"
    volumes:
      - ./app/:/www/app/:z
      - ./scripts/:/www/scripts/:z
