services:
  luovkle.com:
    container_name: luovkle.com
    build:
      context: .
      target: runner
    environment:
      FLASK_DEBUG: true
      FLASK_RUN_PORT: 4000
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - 80:4000
    restart: always
    command: "/runner/.venv/bin/flask run"
    volumes:
      - ./app/:/runner/app/:z
      - ./content/:/runner/content/:z
      - ./scripts/:/runner/scripts/:z
  styles:
    container_name: styles
    build:
      context: .
      target: css-builder
    restart: always
    command: "pnpm run dev:css"
    volumes:
      - ./app/:/css-builder/app/:z
      - ./scripts/:/css-builder/scripts/:z
